"""
Delivery Template Builder — Dynamic template generation based on MILESTONES.md.

Scans the docs_root/MILESTONES.md file for milestone entries and generates
the delivery pipeline with per-milestone auto-flow commands.

Two indicators available:
- delivery-pre: analyse → identify → create-tasks per milestone (before code)
- delivery-pos: qa-gate → mcp-review → sign-off → pending-actions per milestone (after code)
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from workflow_app.domain import CommandSpec, InteractionType, ModelName

logger = logging.getLogger(__name__)

_O = ModelName.OPUS
_S = ModelName.SONNET
_A = InteractionType.AUTO


def _spec(name: str, model: ModelName, pos: int) -> CommandSpec:
    return CommandSpec(
        name=name,
        model=model,
        interaction_type=_A,
        position=pos,
    )


def _discover_milestones(docs_root: str, project_dir: str) -> list[int]:
    """Discover milestone numbers from MILESTONES.md.

    Scans for patterns like "Milestone 1:", "Milestone 2:" in the
    MILESTONES.md file generated by /modules:build-milestones.

    Returns sorted list of milestone numbers (deduplicated).
    """
    milestones_path = Path(project_dir) / docs_root / "MILESTONES.md"
    if not milestones_path.is_file():
        logger.warning("MILESTONES.md not found in %s", docs_root)
        return []

    try:
        content = milestones_path.read_text(encoding="utf-8")
    except Exception as exc:
        logger.error("Failed to read MILESTONES.md: %s", exc)
        return []

    # Match section headers like "Milestone 1:", "Milestone 2: ..."
    # Anchored to start-of-line to avoid duplicate matches from body references
    pattern = re.compile(r"^Milestone\s+(\d+)\s*:", re.IGNORECASE | re.MULTILINE)
    numbers = sorted(set(int(m.group(1)) for m in pattern.finditer(content)))

    if not numbers:
        logger.warning("No milestones found in MILESTONES.md at %s", milestones_path)

    return numbers


def _renumber(specs: list[CommandSpec]) -> list[CommandSpec]:
    """Renumber positions 1..N."""
    for i, spec in enumerate(specs, start=1):
        spec.position = i
    return specs


def build_delivery_template(docs_root: str, project_dir: str) -> list[CommandSpec]:
    """Build the full delivery pipeline template (legacy — plan mode).

    Kept for backward compatibility. Generates /auto-flow delivery-pre milestone-{n}.
    """
    milestones = _discover_milestones(docs_root, project_dir)
    if not milestones:
        logger.error("No milestones found in MILESTONES.md under %s", docs_root)
        return []

    specs: list[CommandSpec] = []
    for n in milestones:
        specs.append(_spec("/clear", _S, 0))
        specs.append(_spec(f"/auto-flow delivery-pre milestone-{n}", _O, 0))

    logger.info(
        "Delivery template built: %d commands for %d milestones",
        len(specs), len(milestones),
    )
    return _renumber(specs)


def build_delivery_plan_template(docs_root: str, project_dir: str) -> list[CommandSpec]:
    """Build delivery PLAN template (before code exists).

    Per milestone: analyse → identify → create-tasks.
    Uses 'delivery-pre' indicator directly — no mode question needed.
    """
    milestones = _discover_milestones(docs_root, project_dir)
    if not milestones:
        logger.error("No milestones found in MILESTONES.md under %s", docs_root)
        return []

    specs: list[CommandSpec] = []
    for n in milestones:
        specs.append(_spec("/clear", _S, 0))
        specs.append(_spec(f"/auto-flow delivery-pre milestone-{n}", _O, 0))

    logger.info(
        "Delivery PLAN template built: %d commands for %d milestones",
        len(specs), len(milestones),
    )
    return _renumber(specs)


def build_delivery_qa_template(docs_root: str, project_dir: str) -> list[CommandSpec]:
    """Build delivery QA template (after code exists).

    Per milestone: qa-gate → fix (if needed) → mcp-review → sign-off → pending-actions.
    Uses 'delivery-pos' indicator directly — no mode question needed.
    """
    milestones = _discover_milestones(docs_root, project_dir)
    if not milestones:
        logger.error("No milestones found in MILESTONES.md under %s", docs_root)
        return []

    specs: list[CommandSpec] = []
    for n in milestones:
        specs.append(_spec("/clear", _S, 0))
        specs.append(_spec(f"/auto-flow delivery-pos milestone-{n}", _O, 0))

    logger.info(
        "Delivery QA template built: %d commands for %d milestones",
        len(specs), len(milestones),
    )
    return _renumber(specs)
